services:
  odoo:
    image: odoo:18.0
    env_file: .env
    depends_on:
      - postgres_odoo
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
    restart: unless-stopped
  postgres_odoo:
    image: postgres:15
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

volumes:
  data:
  db:
